Repository couchbase/couchbase-lite-core, pull requests merged in 2018-02, with the labels that each got.

#395 Convert to asciidoc
  antora.yml
  modules/docs/nav.adoc
  modules/docs/pages/replication-protocol.adoc
Labels: in progress, review

#405 Add link to blog post
  modules/docs/pages/replication-protocol.adoc
Labels: in progress, review

#399 Add message parameter to JNI C4Socket’s closed() method
  Java/jni/native_c4socket.cc
  Java/src/com/couchbase/litecore/C4Socket.java
Labels: in progress, review

#419 Fixed memory-management bug with c4dbobs_getChanges(); API CHANGE!!
  C/c4.def
  C/c4.exp
  C/c4Observer.cc
  C/include/c4Observer.h
  C/tests/c4ObserverTest.cc
  C/tests/c4ThreadingTest.cc
  CSharp/src/LiteCore.Shared/Interop/C4Observer_native.cs
  CSharp/test/LiteCore.Tests.Shared/ObserverTest.cs
  CSharp/test/LiteCore.Tests.Shared/ThreadingTest.cs
  LiteCore/Database/SequenceTracker.cc
  LiteCore/Database/SequenceTracker.hh
  Replicator/DBWorker.cc
Labels: review

#421 Reduce number of file descriptors opened while pulling blobs
  Replicator/IncomingBlob.cc
  Replicator/IncomingBlob.hh
  Replicator/IncomingRev.cc
  Replicator/IncomingRev.hh
  Replicator/Pusher.cc
  Replicator/tests/ReplicatorLoopbackTest.cc
Labels: review

#429 Fix error: [-d: command not found
  build_cmake/scripts/build_macos.sh
Labels: in progress

#430 Java: make SharedKeys thread safe
  Java/jni/native_fleece.cc
  Java/src/com/couchbase/litecore/C4Document.java
  Java/src/com/couchbase/litecore/SharedKeys.java
  Java/src/com/couchbase/litecore/fleece/FLDict.java
  Java/src/com/couchbase/litecore/fleece/FLSharedKeys.java
  Java/src/com/couchbase/litecore/fleece/FLValue.java
  Java/src/com/couchbase/litecore/fleece/MDict.java
Labels: in progress, review

#435 Java: Fixed Stemming is not working for FTS.
  Java/jni/native_c4query.cc
Labels: review
